export const TopicLists = [
  {
    label: "Anime & Cosplay",
    topics: ["Anime & Manga", "Cosplay"],
  },
  {
    label: "Art",
    topics: [
      "Performing Arts",
      "Architecture",
      "Design",
      "Art",
      "Filmmakng",
      "Digital Art",
      "Photography",
    ],
  },
  {
    label: "Business & Finance",
    topics: [
      "Personal Finance",
      "Crypto",
      "Economics",
      "Business News & Discussion",
      "Deals & MarketPlace",
      "Startup & Entrepreneurship",
      "Photography",
    ],
  },
  {
    label: "Education & Career",
    topics: ["Studying & Education", "Career"],
  },
  {
    label: "Fashion & Beauty",
    topics: [
      "Nails",
      "Hair",
      "Fashion",
      "Accessories & Jewelry",
      "Weddings",
      "Tattoos & Piercings",
      "Skincare",
      "Watches",
      "Streetwear",
    ],
  },
  {
    label: "Food & Drinks",
    topics: [
      "Food & Recipe",
      "Baking & Deserts",
      "Barbecues & Grilling",
      "Alcoholic Beverages",
    ],
  },
  {
    label: "Games",
    topics: [
      "Gaming Console & Gear",
      "Esports",
      "Adventure games",
      "Gaming news & Discussion",
      "Action games",
      "Strategy games",
      "Simulation games",
      "Role-playing games",
      "Sports & Racing games",
      "Mobile games",
    ],
  },
  {
    label: "Home & Garden",
    topics: ["House Plants", "Gardening & Farming", "DIY & Crafts"],
  },
  {
    label: "Internet Culture",
    topics: [
      "Memes",
      "Funny",
      "Wholesome & HeartWarming",
      "Interesting",
      "Oddly satisfying",
    ],
  },
  {
    label: "Movies & TV",
    topics: [
      "Comedy Movies & Series",
      "Action Movies & Series",
      "Fanstasy Movies & Series",
      "Documentary Movies & Series",
      "Drama Movies & Series",
      "Crime,Mystery & Thriller Movies & Series",
      "Animated Movies & Series",
      "Sci-Fi Movies & Series",
      "Romance Movies & Series",
      "Superhero Movies & Series",
      "Horror Movies & Series",
      "Movie news & Discussion",
      "TV news & Discussion",
    ],
  },
  {
    label: "Music",
    topics: [
      "Musical Instruments & Singing",
      "Classical Music",
      "Music News & Discussions",
      "Country Music",
      "Hip-hop & Rap Music",
      "Jazz Music",
      "Rock Music",
      "Pop Music",
      "Metal Music",
      "Music Production",
      "Other Music Genres",
    ],
  },
  {
    label: "Nature & Outdoors",
    topics: ["Fishing", "Camping & Hiking ", "Hunting", "Nature & Wildlife"],
  },
  {
    label: "News & Politics",
    topics: ["News", "Activism ", "Politics"],
  },
  {
    label: "Places & Travel",
    topics: [
      "Places in Europe",
      "Places in Asia",
      "Places in North America ",
      "Places in middle East",
      "Places in Africa",
      "Travel & Holiday",
    ],
  },
  {
    label: "Pop Culture",
    topics: [
      "Generation & Nostalgia",
      "Creators & Influencers",
      "Celebrities ",
      "Podcasts",
      "Streamers",
    ],
  },
  {
    label: "Sciences",
    topics: [
      "Biological Sciences",
      "Engineering",
      "Physics ",
      "Mathematics",
      "Climate & Environment",
      "Psychology & Socialogy",
      "Geography",
      "Chemistry",
      "Other Sciences",
    ],
  },
  {
    label: "Spooky",
    topics: [
      "Paranormal & Unexplained",
      "Weird & Unusual",
      "True Crime ",
      "Creepy",
    ],
  },
  {
    label: "Sports",
    topics: [
      "Basketball",
      "Soccer",
      "Boxing",
      "Arnis",
      "Volleyball",
      "Tennis",
      "Bowling",
      "Sport News & Discussion",
      "Other Sports",
    ],
  },
  {
    label: "Technology",
    topics: [
      "Cosumer & Electronics",
      "DIY Electronics",
      "Artificial Intelligence & Machine Learning ",
      "Computer & Hardware",
      "Programming",
      "Software & Apps",
      "3D Printing",
      "Tech News & Discussion",
      "Other technologies",
    ],
  },
  {
    label: "Vechicles",
    topics: ["Motorcycles", "Car & Trucks", "Trains & Public Transportation "],
  },
  {
    label: "Wellness",
    topics: [
      "Diet & Nutrition",
      "Motivation & Self-Improvement",
      "Fitness",
      "Weight Loss",
    ],
  },
];
