import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import { Toaster } from "@/components/ui/Toaster";
import Providers from "@/components/Provider";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          "relative h-full font-sons antialiased",
          poppins.className
        )}
      >
        <Providers>
          <main className="relative flex flex-col min-h-screen">
            <div className="flex-grow flex-1 ">{children}</div>
            <Toaster />
          </main>
        </Providers>
      </body>
    </html>
  );
}
