import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import { Toaster } from "@/components/ui/Toaster";
import Providers from "@/components/utils/Provider";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("min-h-screen font-sons antialiased", poppins.className)}
      >
        <Providers>
          <div className="mx-auto dark:bg-neutral-900">{children}</div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
